# Generated by Django 4.2.6 on 2023-10-25 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=30, verbose_name='Телефонный номер')),
                ('instagram', models.URLField(verbose_name='инстаграмм')),
                ('whatsapp', models.URLField(verbose_name='ватсап')),
            ],
            options={
                'verbose_name': ('Контакты',),
                'verbose_name_plural': 'Контакт',
            },
        ),
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Заголовок')),
                ('descriptions', models.CharField(blank=True, max_length=255, null=True, verbose_name='Описание')),
                ('logo', models.ImageField(upload_to='geeks_logo/', verbose_name='Логотип')),
            ],
            options={
                'verbose_name': ('Основная Настройка',),
                'verbose_name_plural': 'Основные Настройки',
            },
        ),
    ]
