# Generated by Django 4.2.6 on 2023-10-26 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='geeks_logo/', verbose_name='Логотип'),
        ),
    ]
