# Generated by Django 4.2.6 on 2023-10-27 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0004_alter_settings_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image_1',
            field=models.ImageField(default=1, upload_to='geeks_image/', verbose_name='Фотография_1'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image_2',
            field=models.ImageField(default=1, upload_to='geeks_image/', verbose_name='Фотография_2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image_3',
            field=models.ImageField(default=1, upload_to='geeks_image/', verbose_name='Фотография_3'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image_4',
            field=models.ImageField(default=1, upload_to='geeks_image/', verbose_name='Фотография_4'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='settings',
            name='image_5',
            field=models.ImageField(default=1, upload_to='geeks_image/', verbose_name='Фотография_5'),
            preserve_default=False,
        ),
    ]
