# Generated by Django 4.2.6 on 2023-10-28 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0005_settings_image_1_settings_image_2_settings_image_3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image_0',
            field=models.ImageField(default=1, upload_to='geeks_2image/', verbose_name='Фотография_2'),
            preserve_default=False,
        ),
    ]
