# Generated by Django 4.2.6 on 2023-10-28 11:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0006_settings_image_0'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'verbose_name': ('Контакт',), 'verbose_name_plural': 'Контакты'},
        ),
    ]
