# Generated by Django 4.2.6 on 2023-10-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0007_alter_contact_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Blog_detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Заголовок')),
                ('descripton', models.CharField(max_length=255, verbose_name='Описание')),
            ],
            options={
                'verbose_name': (' Blog',),
                'verbose_name_plural': 'Blog',
            },
        ),
    ]
