# Generated by Django 4.2.6 on 2023-10-30 11:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0008_blog_detail'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Blog_detail',
            new_name='Blog_details',
        ),
    ]
