# Generated by Django 4.2.6 on 2023-10-30 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0009_rename_blog_detail_blog_details'),
    ]

    operations = [
        migrations.AlterField(
            model_name='settings',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='geeks_image/', verbose_name='Фотография'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_0',
            field=models.ImageField(blank=True, null=True, upload_to='geeks_2image/', verbose_name='Фотография_2'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='geeks_image/', verbose_name='Фотография_1'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='geeks_image/', verbose_name='Фотография_2'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_3',
            field=models.ImageField(blank=True, null=True, upload_to='geeks_image/', verbose_name='Фотография_3'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_4',
            field=models.ImageField(blank=True, null=True, upload_to='geeks_image/', verbose_name='Фотография_4'),
        ),
        migrations.AlterField(
            model_name='settings',
            name='image_5',
            field=models.ImageField(blank=True, null=True, upload_to='geeks_image/', verbose_name='Фотография_5'),
        ),
    ]
