# Generated by Django 4.2.6 on 2023-10-31 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geeks', '0011_gallery_delete_blog_details_remove_settings_image_0_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='geeks_image/', verbose_name='Фотография'),
        ),
    ]
